### ISSUE TITLE
Version 2.9.1 fails with an exception on Mac M1

### ISSUE THREAD

**Issue by cianoc** [csound-plugins/risset#5]
I installed risset 2.9.1 using pipx on an ARM Mac.

Python version is 3.12.3

When I type any command (e.g. `risset list`) it fails with the following traceback:
```
Csound Version: 6180

Traceback (most recent call last):
  File "/Users/cianoconnor/.local/bin/risset", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cianoconnor/.local/pipx/venvs/risset/lib/python3.12/site-packages/risset.py", line 3306, in main
    ok = args.func(mainindex, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cianoconnor/.local/pipx/venvs/risset/lib/python3.12/site-packages/risset.py", line 2781, in cmd_list
    return mainindex.list_plugins(installed=args.installed, nameonly=args.nameonly, oneline=args.oneline,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cianoconnor/.local/pipx/venvs/risset/lib/python3.12/site-packages/risset.py", line 2329, in list_plugins
    info = self.installed_plugin_info(plugin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cianoconnor/.local/pipx/venvs/risset/lib/python3.12/site-packages/risset.py", line 2008, in installed_plugin_info
    binary = plugin.find_binary()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/cianoconnor/.local/pipx/venvs/risset/lib/python3.12/site-packages/risset.py", line 823, in find_binary
    if b.platform == platformid and b.matches_versionid(csound_version)]
       ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'platform'
```

**Comment by gesellkammer** [comment]
Can you try updated version (2.9.2) ?

**Comment by gesellkammer** [comment]
All tests are passing here: https://cirrus-ci.com/task/6199232233734144

**Comment by cianoc** [comment]
Yes, after purging the risset plugin directory it worked. Thanks.
